name: Deploy to Netlify

on:
  push:
    branches:
      - main  # or master, depending on your default branch name
  pull_request:
    types: [opened, synchronize]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: 1.1.29

      - name: Install dependencies
        working-directory: apps/lanonasis-index
        run: bun install --frozen-lockfile

      - name: Build
        working-directory: apps/lanonasis-index
        run: bun run build

      - name: Install Netlify CLI
        run: bun add -g netlify-cli
        working-directory: apps/lanonasis-index

      - name: Deploy to Netlify
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        run: netlify deploy --prod --dir=dist
        working-directory: apps/lanonasis-index

      - name: Comment on PR with deploy URL
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { issue: { number: issue_number }, repo: { owner, repo } } = context;
            github.rest.issues.createComment({
              issue_number,
              owner,
              repo,
              body: `✅ Netlify Preview deployed at: https://deploy-preview-${issue_number}--${process.env.NETLIFY_SITE_ID}.netlify.app`
            })